"""Factual Consistency Module Top-Level Facade.

Re-exports cross-session consistency checking, claim storage,
and contradiction detection.
"""

from __future__ import annotations

from consistency import (
    CORE_POSITIONS,
    IKHTILAF_MAP,
    ClaimStore,
    ClaimType,
    CoherenceMetrics,
    ConsensusLevel,
    ConsistencyAction,
    ConsistencyAlert,
    ConsistencyAlertManager,
    ConsistencyCheckResult,
    ConsistencyEnforcer,
    Contradiction,
    ContradictionCategory,
    ContradictionSeverity,
    CorePosition,
    FactualClaim,
    InMemoryClaimStore,
    RedisClaimStore,
    RulingType,
    consistency_router,
    create_claim_store,
    detect_contradictions,
    extract_claims,
    format_reconciliation_note,
    get_alert_manager,
    get_consistency_enforcer,
    get_core_position,
    get_ikhtilaf_entry,
    is_core_principle_violation,
    normalize_text_for_claim,
    reconcile_response_text,
)

__all__ = [
    "CORE_POSITIONS",
    "IKHTILAF_MAP",
    "ClaimStore",
    "ClaimType",
    "CoherenceMetrics",
    "ConsensusLevel",
    "ConsistencyAction",
    "ConsistencyAlert",
    "ConsistencyAlertManager",
    "ConsistencyCheckResult",
    "ConsistencyEnforcer",
    "Contradiction",
    "ContradictionCategory",
    "ContradictionSeverity",
    "CorePosition",
    "FactualClaim",
    "InMemoryClaimStore",
    "RedisClaimStore",
    "RulingType",
    "consistency_router",
    "create_claim_store",
    "detect_contradictions",
    "extract_claims",
    "format_reconciliation_note",
    "get_alert_manager",
    "get_consistency_enforcer",
    "get_core_position",
    "get_ikhtilaf_entry",
    "is_core_principle_violation",
    "normalize_text_for_claim",
    "reconcile_response_text",
]
